### ISSUE TITLE
Images used for style transfer

### ISSUE THREAD

**Issue by uzpaka** [naver/r2d2#12]
Hello, I am interested in the images you used for transferring the style of a Aachen night image into a day image. If I look at the provided dataset, the image names contain the name of the day image, but not the original name of the night image you used for the style transfer. For example, the image '1031.jpg.st_3473.jpg' corresponds to the day image '1031.jpg', but I cannot find any '3473.jpg' in the set of night images. Could you tell me how I can find out which night images you used, please?

Also, which style transfer model did you use? I couldn't find it in the paper.

Thank you and kind regards

**Comment by humenbergerm** [comment]
Hi!

We used https://github.com/NVIDIA/FastPhotoStyle to transfer day images into night images. As style image we downloaded random night-time images from the city of Aachen. I hope that helps.

Best,
Martin

**Comment by uzpaka** [comment]
Thank you! Are the random images you used available to us?

Best,
Ali

**Comment by humenbergerm** [comment]
Sorry we don't have them anymore. They got lost :(

**Comment by uzpaka** [comment]
Ok!
