### ISSUE TITLE
How to solve warning about "torch.nn.functional.grid_sample()" due to Pytorch version  1.3.0.

### ISSUE THREAD

**Issue by GabbySuwichaya** [naver/r2d2#13]
I have received the warning about "torch.nn.functional.grid_sample()" due to Pytorch version  1.3.0.
Can you tell us how to solve this warning ? It seems that it does matter to check whether  **align_corners**=**True** or **False** for this function. 

 
The following pictures display the location where I received the warning and the warning message.
![Screenshot from 2020-05-13 22-06-06](https://user-images.githubusercontent.com/49115268/81817151-416c2d00-9567-11ea-8544-a70de8050626.png)

![Screenshot from 2020-05-13 22-12-09](https://user-images.githubusercontent.com/49115268/81817300-809a7e00-9567-11ea-8b2f-03fac26ecc6d.png)

**Comment by jrevaud** [comment]
I was using pytorch 1.1 at the time, and `the default behavior up to version 1.2.0 was align_corners = True`

But I'm not sure if it will change much in the end anyway :)

**Comment by GabbySuwichaya** [comment]
Got it... Thanks for the answer. :)
