### ISSUE TITLE
Could you tell me your training and feature extracting setting for local feature challenge in visual localization benchmark

### ISSUE THREAD

**Issue by hongsiyu** [naver/r2d2#14]
I trained R2D2 following your default setting in your code and paper. But I didn't achieve the best performance on Aachen dataset in your paper.

**Comment by humenbergerm** [comment]
model_path: r2d2_WASF_N8_big.pt
scale_f: 1.189207115002721
min_scale: 0.3
max_scale: 1
min_size: 128
max_size: 9999
max_keypoints: 40000
reliability_thr: 0.7
repeatability_thr: 0.7

**Comment by jrevaud** [comment]
There is quite a lot of variance on the Aachen, because it depends on RANSAC which is random.
If you submit several times the same thing, you'll see that you obtain different results.

This is not a problem of R2D2, it's due to the way the benchmark is implemented and it's the same for all methods.
