### ISSUE TITLE
Typo in reliability loss equation in paper

### ISSUE THREAD

**Issue by rsokl** [naver/r2d2#15]
![image](https://user-images.githubusercontent.com/29104956/82936755-0dc4d600-9f5d-11ea-9b23-3e73a3a96036.png)

^ this should be a minus sign in the paper (the code has the appropriate sign)

**Comment by jrevaud** [comment]
yes!
I apologize, there is a typo indeed.
(and this is the reliabillity loss, not the repeatability loss)
