### ISSUE TITLE
Generate image pairs using random homography

### ISSUE THREAD

**Issue by hanyunlong233** [naver/r2d2#17]
hello!
   I want to use my own data to fine-tune your model to better fit our scene. I need to build my own training data set. According to the random homography mentioned in your article, could you please give me some advice?

**Comment by humenbergerm** [comment]
Hi!

Have you already tried the ones we suggested in the training code? We tried to find good settings for the task of visual localization where the features should be robust (not invariant) against viewpoint changes. I would start with this.

Best,
Martin

**Comment by hanyunlong233** [comment]
Thank you for your reply.I've already started my fine tuning.I think your model is very good, but my data is very special and needs to be fine-tuned.Thank you very much for your advice.
