### ISSUE TITLE
Visualize heatmap

### ISSUE THREAD

**Issue by dzungdoan6** [naver/r2d2#19]
Hi, thank you for the significant work. I really enjoy your paper.

I would like to visualize the heatmap of repeatability and reliability (as Fig 6). Could you please guide me how to do it?

Thank you

**Comment by jerome-revaud** [comment]
Hi

Hmm good question. For the paper we wrote some code to generate figure 6, and I have to dig up a little to find it.
[...] 
Ok, i found some old code which i cleaned a little bit. Here is how it works:

```bash
git pull
python viz_heatmaps.py --img imgs/peppers.png --checkpoint models/r2d2_WASF_N16.pt --gpu 0
```
You should see:
![viz](https://user-images.githubusercontent.com/56719813/87534248-0c2ea900-c696-11ea-9284-f5175d268d65.png)
