### ISSUE TITLE
How to evaluate the model on Hpatches and visualize the results using .ipynb?

### ISSUE THREAD

**Issue by whubaichuan** [naver/r2d2#22]
Hi, if I get a .r2d2 extension (including descriptors.npy, imsize.npy, keypoints.npy and scores.npy) after running the extract.py, how can I evaluate it on Hpatches and visualize the results using d2-net/hpatches_sequences/HPatches-Sequences-Matching-Benchmark.ipynb?

**Comment by whubaichuan** [comment]
First, you can add 'r2d2' in the methods in HPatches-Sequences-Matching-Benchmark.ipynb.
Second, if you meet the error about the ‘IntProgress‘, you can input 'conda install ipywidgets'.
Third, you can add the name of the existing .npy file in the methods to visualize the results.

**Comment by water-wave** [comment]
> First, you can add 'r2d2' in the methods in HPatches-Sequences-Matching-Benchmark.ipynb.
> Second, if you meet the error about the ‘IntProgress‘, you can input 'conda install ipywidgets'.
> Third, you can add the name of the existing .npy file in the methods to visualize the results.
I have meet the same problem.can you tell me the detail about how to evaluate on Hpatches. thanks.

**Comment by water-wave** [comment]
I have meet the same problem.can you tell me the detail about how to evaluate on Hpatches. thanks.

**Comment by whubaichuan** [comment]
First, you can add 'r2d2' in the methods in HPatches-Sequences-Matching-Benchmark.ipynb.
Second, if you meet the error about the ‘IntProgress‘, you can input 'conda install ipywidgets'.
Third, you can add the name of the existing .npy file in the methods to visualize the results.

**Comment by whubaichuan** [comment]
@water-wave

**Comment by whubaichuan** [comment]
@water-wave First, you can add 'r2d2' in the methods in HPatches-Sequences-Matching-Benchmark.ipynb.
Second, if you meet the error about the ‘IntProgress‘, you can input 'conda install ipywidgets'.
Third, you can add the name of the existing .npy file in the methods to visualize the results.

**Comment by pfvaldez** [comment]
@whubaichuan thank you for the info.
I have a question after running the `extract.py`, I only get an output file with `.r2d2` extension.
How did you get the `.npy` files such as `(including descriptors.npy, imsize.npy, keypoints.npy and scores.npy)` you mentioned?
Thanks.

**Comment by Ma0zii** [comment]
> @whubaichuan thank you for the info. I have a question after running the `extract.py`, I only get an output file with `.r2d2` extension. How did you get the `.npy` files such as `(including descriptors.npy, imsize.npy, keypoints.npy and scores.npy)` you mentioned? Thanks.

I have run the `extra.py` and get the `.r2d2` files, but I don't know how to evaluate on Hpatches. Can you tell me how to do that? Thank you very much!
