### ISSUE TITLE
How do you implement feature extraction for large-sized images?

### ISSUE THREAD

**Issue by ahong007007** [naver/r2d2#3]
Hello, great paper and work,thank you .

How do you implement feature extraction for large-sized images? The paper is limited to 1024 pixels, and the zoom factor cannot be greater than 1.

**Comment by jerome-revaud** [comment]
Hi @ahong007007 

The approach has no problem with large-sized images. 
The command line is as follows:

```bash
python extract.py --model model.pt --images image.jpg --top-k 5000 --min-size 0 --max-size 9999 --min-scale 0.3 --max-scale 1.0
```

*Note*: In my implementation, a zoom factor = 1 means full-image size, and = 1/2 means half the resolution.
