### ISSUE TITLE
The problem downloading the revisitop1m dataset

### ISSUE THREAD

**Issue by pixelsmaker** [naver/r2d2#36]
I can't download the revisitop1m datasets, it seems downloading speed is really low, and the downloading somtimes broke out.

**Comment by humenbergerm** [comment]
Hi! 

Unfortunately, we are not the ones hosting this dataset. Sorry!

Best,
Martin

**Comment by pixelsmaker** [comment]
OK, but can you tell me the difference between resolution 1024px and full? I find that the  longer edge of the picture in revisitop1m is 1024px

**Comment by pixelsmaker** [comment]
And if I want to train the model only using revisitop1m in resolution full to reproduce the results, what parameters I should change to in train.py?

**Comment by jerome-revaud** [comment]
@pixelsmaker revisitop1m is not the only dataset we used for training. We also used Aachen, and this one contains images larger than 1024 pixels.  For revisitop1m, indeed the default size == full.
