### ISSUE TITLE
Some details about Oxford dataset

### ISSUE THREAD

**Issue by ThompsonHe** [naver/r2d2#39]
Hi, sorry for bothering, when I try to reproduce the network's performance on oxford dataset, I was stuck by the process of using DoG detector to detect keypoints on an image. I am wondering whether the DoG detector is implemented by yourself or you just resort  to some open source code(If so, could you please provide me the link?). Thank You!!!

**Comment by jerome-revaud** [comment]
You can find many implementations of the DoG detector, e.g. in OpenCV or VLFeat.
