### ISSUE TITLE
Reproduce the results in the paper

### ISSUE THREAD

**Issue by pengsida** [naver/r2d2#4]
Hi,

Thanks for your excellent paper and code for the feature detection.
In this repo, you only released the MMA metric.
I want to test the pretrained model on repeatibility, matching score and visual localization.
Could you tell me the specific detail on the repeatibility and matching score metric?
And could you tell me the localization pipeline used in your experiment?

**Comment by humenbergerm** [comment]
Hi!

For visual localization, we used this pipeline: https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation
It was part of the local feature task of the LTVL challenge at CVPR19.

Best,
Martin

**Comment by pengsida** [comment]
Thank you!
