### ISSUE TITLE
Why the time of feature extraction is more than superpoint?

### ISSUE THREAD

**Issue by OldAAAA** [naver/r2d2#40]
I notice the weight number of r2d2 is less than superpoint, but the time r2d2 used to extract feature is more than superpoint in my machine.
There is a GTX 1660Ti GPU in my machine,the time superpoint used to extract feature is about 0.03ms, but  r2d2 is about 0.08(not the muti-scale).My input is a 640 * 480 picture.

**Comment by jerome-revaud** [comment]
Hi @OldAAAA 
Yes, so this is normal. R2D2 is quite computationally expensive, unfortunately.
Usually in a CNN, there are pooling stage that progressively reduce the spatial dimension while augmenting the number of channels. Not with R2D2, where dilated convolutions are used instead (see paper). This helps maintaining a good localization of the keypoints, but it's quite costly.
