### ISSUE TITLE
Require for the image data of Zero

### ISSUE THREAD

**Issue by Katherinaxxx** [naver/r2d2#47]
Hello,
  Thanks for your great work!
  However, when I try to download the images of zero datasets from image_url, sometimes I will come across a '404 error'. And it really takes a very long time to download from the website links.
  So can you offer images of zero datasets?

**Comment by jerome-revaud** [comment]
Hey @Katherinaxxx 
Can you be more specific please? not sure what is the "zero dataset" you're mentioning.

**Comment by Katherinaxxx** [comment]
Never mind, I made a mistake.
