### ISSUE TITLE
How can one pixel of the image correspond to a feature point and a descriptor? 

### ISSUE THREAD

**Issue by ahong007007** [naver/r2d2#6]
Thank you for your wonderful work.

In the paper, a feature point and a descriptor are extracted for each image patch. How can one pixel of the image correspond to a feature point and a descriptor? Thank you.

**Comment by humenbergerm** [comment]
Hi!

Repeatability, reliability, and descriptor are computed for each pixel. Then we apply non-maximum suppression on repeatability and reliability and keep the top-n (highest rep*rel score) pixel locations as keypoints (+descriptor). 

Best,
Martin
