### ISSUE TITLE
How to reproduce the detector repeatability on the Oxford dataset ?

### ISSUE THREAD

**Issue by djkim3** [naver/r2d2#7]
Hi,
I tested detector repeatability using pretrained models and the Oxford dataset. But my results was not same with paper's. (My results are half or less than the paper.)

I followed the method of 'Scale & affine invariant interest point detectors' that consider that two points A and B correspond if the error in relative point location is less than 1.5pixel.
(In serction 4.1, you said you followed this paper)([LINK](https://www.robots.ox.ac.uk/~vgg/research/affine/det_eval_files/mikolajczyk_ijcv2004.pdf))
A is keypoints of image 1 and B is points of image 2, 3, ...
![image](https://user-images.githubusercontent.com/34887555/74125126-b2721080-4c17-11ea-9a40-77264931c769.png)

Could you tell me how experiment the repeatibility test? or Could you upload the code about that experiment?

**Comment by jerome-revaud** [comment]
Hi
see issue #8
